name: vecvfluttertool
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0  # Downgraded to a version compatible with SDK 33
  share_plus: ^6.0.0  # Version compatible with SDK 33
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.12  # Version compatible with SDK 33

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
